### ISSUE TITLE
APIG访问北京四出现SslHandShakeException

### ISSUE THREAD

**Issue by aijingsun6** [huaweicloud/huaweicloud-sdk-python-v3#17]
requests.exceptions.SSLError: HTTPSConnectionPool(host='apig.cn-north-4.myhuaweicloud.com', port=443): Max retries exceeded with url: /v2/***************/apigw/instances (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

**Comment by mawenbo-huawei** [comment]
https://github.com/huaweicloud/huaweicloud-sdk-python-v3/blob/master/README_CN.md#14-ssl-%E9%85%8D%E7%BD%AE-top
