### ISSUE TITLE
BSS接口ListPayPerUseCustomerResources能不能加一个字段，查询到期不续费或者手动续费等选项的

### ISSUE THREAD

**Issue by 775838893** [huaweicloud/huaweicloud-sdk-python-v3#18]
![image](https://user-images.githubusercontent.com/7666283/173020426-95187867-2bf1-4659-a95a-fe703da66527.png)
希望在这个接口ListPayPerUseCustomerResources加一个功能，可以查询手动续费，自动续费或者到期不续费的状态。

**Comment by 775838893** [comment]
或者能返回能识别这种状态的字段也可以。

**Comment by mawenbo-huawei** [comment]
已经反馈给BSS服务，如果比较急可以在华为云控制台上给对应云服务提交工单。

**Comment by 775838893** [comment]
提过的。貌似还没有解决。我们希望能通过这个字段的状态，只筛选手动续费的，以便通知到对应的人让他们确定是否续费。

**Comment by pwx298342** [comment]
![image](https://user-images.githubusercontent.com/107245987/173025082-38f5b107-e47e-4faf-aa61-8cf97d0fb2ff.png)expire_policy 看下这个响应字段是不是可以解决你的问题？

**Comment by 775838893** [comment]
试过啦，不管是不是手动续费都是4

**Comment by mawenbo-huawei** [comment]
这个问题反馈属于BSS服务，我先关掉这个issue了
