### ISSUE TITLE
http_utils.py报错，get_dict_params方法没定义

### ISSUE THREAD

**Issue by jackie066** [huaweicloud/huaweicloud-sdk-python-v3#19]
调用sdk时报了这个错： 
File "/usr/local/lib/python3.8/site-packages/huaweicloudsdkcore/client.py", line 278, in _parse_path_params path_params = http_utils.parameters_to_tuples(path_params, collection_formats) File "/usr/local/lib/python3.8/site-packages/huaweicloudsdkcore/utils/http_utils.py", line 113, in parameters_to_tuples dict_params = get_dict_params(k, v) NameError: name 'get_dict_params' is not defined
看了一下发现没有 get_dict_params 这个方法

**Comment by mawenbo-huawei** [comment]
请问您调用的是哪个服务的哪个接口？使用的sdk的版本号是多少？

**Comment by jackie066** [comment]
> 请问您调用的是哪个服务的哪个接口？使用的sdk的版本号是多少？

调用负载服务的查询负载列表的接口，sdk版本是最新的

**Comment by jackie066** [comment]
> 请问您调用的是哪个服务的哪个接口？使用的sdk的版本号是多少？
我看了一下 huaweicloudsdkcore/utils/http_utils.py 这个文件里没有get_dict_params这个方法

**Comment by mawenbo-huawei** [comment]
这是个问题，方便发下请求体的构造吗，都传了哪些参数，类似这样
```python
request = ListLoadbalancersRequest()
request.operating_status = "ONLINE"
request.provisioning_status = "ACTIVE"
request.vip_address = "vip_address"
request.vpc_id = "vpc_id"
response = client.list_loadbalancers(request)
```

**Comment by jackie066** [comment]
> 这是个问题，方便发下请求体的构造吗，都传了哪些参数，类似这样
> 
> ```python
> request = ListLoadbalancersRequest()
> request.operating_status = "ONLINE"
> request.provisioning_status = "ACTIVE"
> request.vip_address = "vip_address"
> request.vpc_id = "vpc_id"
> response = client.list_loadbalancers(request)
> ```

  request = ListLoadbalancersRequest()
  response = client.list_loadbalancers(request)

**Comment by mawenbo-huawei** [comment]
太久时间没回复先关闭这个问题了，有问题请重新提交
