### ISSUE TITLE
功能需求：ECS 增加 NovaLockServer 函数

### ISSUE THREAD

**Issue by Adek06** [huaweicloud/huaweicloud-sdk-python-v3#20]
## 背景
我们生产环境中，有时需要动态的保护某些 ecs 不被其它组件删除或停止。

我在 [api 文档](https://console.huaweicloud.com/apiexplorer/#/apidebug/ECS/sdk?api=NovaLockServer) 里注意到有这个接口，但 SDK 里却不支持

我们需要在能依靠官方提供的 SDK 来实现，而不是自己来维护这个接口

**Comment by mawenbo-huawei** [comment]
已反馈给ECS服务，会在本周发布的新版本SDK中上线该接口

**Comment by Adek06** [comment]
@mawenbo-huawei 谢谢，也请留意一下 NovaUnlockServer 接口
