### ISSUE TITLE
Ecs规格实例支持规格单个或多个实例查询

### ISSUE THREAD

**Issue by shiftwinting** [huaweicloud/huaweicloud-sdk-python-v3#21]
https://ecs.cn-east-2.myhuaweicloud.com/v1/{project_id}/cloudservers/flavors

文档不支持 实例规格查询，目前只能手动过滤，性能太差了

**Comment by GaoLeiQin** [comment]
暂不支持

**Comment by shiftwinting** [comment]
后期有没有计划，可以支持，
谢谢

**Comment by mawenbo-huawei** [comment]
这个问题关闭了，后续有问题请重新提交issue，建议登录[华为云控制台](https://auth.huaweicloud.com/authui/login.html?service=https%3A%2F%2Fconsole.huaweicloud.com%2Fconsole%2F#/login) -> 提交工单来反馈云服务接口以及参数的问题。
