### ISSUE TITLE
huaweicloudsdkcdn 广州region异常

### ISSUE THREAD

**Issue by sulin2018** [huaweicloud/huaweicloud-sdk-python-v3#22]
测试代码:
`
from huaweicloudsdkcdn.v1.region.cdn_region import CdnRegion
from huaweicloudsdkcore.exceptions import exceptions
from huaweicloudsdkcdn.v1 import *

credentials = GlobalCredentials(self.ak, self.sk)
client = (
            CdnClient.new_builder()
            .with_credentials(credentials)
            .with_region(CdnRegion.value_of("cn-south-1"))
            .build()
        )
`

**Comment by mawenbo-huawei** [comment]
CDN服务是一个全局的服务，所有region对应访问的endpoint都是同一个，使用cn-north-1即可
