### ISSUE TITLE
OBS

### ISSUE THREAD

**Issue by CraftedCat** [huaweicloud/huaweicloud-sdk-python-v3#23]
How to list all s3 buckets?
i am trying from huaweicloudsdkmpc.v1 import MpcClient, ListAllBucketsRequest, ListAllObsObjListRequest
mpc_client.list_all_buckets(request)

but get error:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><Code>AccessDenied</Code><Message>AWS authentication requires a valid Date or x-amz-date header</Message><RequestId></RequestId><HostId></HostId></Error>
403

**Comment by mawenbo-huawei** [comment]
It seems that the request header `Date` is missing, and the problem has been reported to the MPC service, thank you for your feedback.

**Comment by huangmins** [comment]
Add a request header, for example, "X-Sdk-Date": "20230517T135124Z",

**Comment by huangmins** [comment]
Use apie to debug api:     https://apiexplorer.developer.huaweicloud.com/apiexplorer/debug?product=MPC&api=ListAllBuckets
![image](https://github.com/huaweicloud/huaweicloud-sdk-python-v3/assets/50950904/5f06f1f4-d027-4a12-9aab-52f19f5879aa)

**Comment by huangmins** [comment]
Use apie to debug api: https://apiexplorer.developer.huaweicloud.com/apiexplorer/debug?product=MPC&api=ListAllBuckets

**Comment by mawenbo-huawei** [comment]
The code works for me.

```python
# coding: utf-8

from huaweicloudsdkcore.auth.credentials import BasicCredentials
from huaweicloudsdkmpc.v1.region.mpc_region import MpcRegion
from huaweicloudsdkcore.exceptions import exceptions
from huaweicloudsdkmpc.v1 import *

if __name__ == "__main__":
    ak = "<YOUR AK>"
    sk = "<YOUR SK>"

    credentials = BasicCredentials(ak, sk)

    client = MpcClient.new_builder() \
        .with_credentials(credentials) \
        .with_region(MpcRegion.value_of("cn-north-4")) \
        .build()

    try:
        request = ListAllBucketsRequest()
        response = client.list_all_buckets(request)
        print(response)
    except exceptions.ClientRequestException as e:
        print(e.status_code)
        print(e.request_id)
        print(e.error_code)
        print(e.error_msg)
```

**Comment by mawenbo-huawei** [comment]
No reply has been received. If you still have any questions, submit the issue again.
