### ISSUE TITLE
请问支持哪些语种？在什么地方能够看到？

### ISSUE THREAD

**Issue by aixuedegege** [huaweicloud/huaweicloud-sdk-python-v3#27]
阿拉伯语支持么？

**Comment by mawenbo-huawei** [comment]
请问具体什么场景？运行环境是阿拉伯吗？

**Comment by aixuedegege** [comment]
想识别阿拉伯语的语音，有在线试用的么，看一下准确性。还有现在不确定是离线服务还是在云端提供服务，需要先看下效果。

**Comment by mawenbo-huawei** [comment]
https://console.huaweicloud.com/apiexplorer/#/openapi/overview 这里可以使用在线API/SDK调试

**Comment by mawenbo-huawei** [comment]
这个问题关闭了，如还有其他疑问请重新打开issue，或者创建新的issue，谢谢。
