### ISSUE TITLE
Region验证移出SDK代码，改为服务后端验证

### ISSUE THREAD

**Issue by ChainsDW** [huaweicloud/huaweicloud-sdk-python-v3#28]
在使用或申请新的region资源时，sdk里没有region就要更新sdk版本，这样太离谱，更新后不确定会对现有代码有影响。建议取消sdk的本地region验证

**Comment by mawenbo-huawei** [comment]
参考下自定义region配置，https://github.com/huaweicloud/huaweicloud-sdk-python-v3/blob/master/README_CN.md#332-Region%E9%85%8D%E7%BD%AE-top
