### ISSUE TITLE
你们平台那个日志详情少的可怜 怎么拿来让开发者做生态

### ISSUE THREAD

**Issue by cdxiaodong** [huaweicloud/huaweicloud-sdk-python-v3#30]
header匹配日志详情缺少唯一特征   是不是不打算让开发者使用

**Comment by cdxiaodong** [comment]
部分函数没有http_info接口 ->进而没有invoker追踪  不知道是不是你们所谓的"合规"需求 但我知道像阿里云是有的  而且你们的调试平台都有这类接口   是你们不想开放还是什么原因？

**Comment by cdxiaodong** [comment]
云审计平台只支持API调用台捕捉的日志 不支持本地代码层捕捉的日志

**Comment by mawenbo-huawei** [comment]
> 部分函数没有http_info接口 ->进而没有invoker追踪 不知道是不是你们所谓的"合规"需求 但我知道像阿里云是有的 而且你们的调试平台都有这类接口 是你们不想开放还是什么原因？

请问是指API Explorer调试平台开放的云服务接口，SDK中没有对应的接口吗？如果是这样请反馈哪个服务的哪个接口，如果需要更快的反馈，请在华为云控制台提交工单。

**Comment by mawenbo-huawei** [comment]
> 云审计平台只支持API调用台捕捉的日志 不支持本地代码层捕捉的日志

云服务API的问题，建议通过华为云控制台给对应云服务提交工单反馈。

**Comment by mawenbo-huawei** [comment]
没有收到回复，这个问题先关闭了。有问题请重新提交issue或者在华为云控制台提交工单，谢谢！
