### ISSUE TITLE
list_share_backup方法无法调用

### ISSUE THREAD

**Issue by cdxiaodong** [huaweicloud/huaweicloud-sdk-python-v3#34]
list_share_backups对应方法的request 在最新版的rds中有 在api exploer也能调试  但是list_share_backups这个方法却在代码中不能调用 请问它对应的其他适配的core等文件的版本是什么

**Comment by mawenbo-huawei** [comment]
有没有报错信息或者截图

**Comment by cdxiaodong** [comment]
我自己的问题 整好了 我昨晚把issue close了好像
