### ISSUE TITLE
没有DNS域名解析记录的封装么？

### ISSUE THREAD

**Issue by linda-202009** [huaweicloud/huaweicloud-sdk-python-v3#5]

**Comment by Huaweicloud-SDK** [comment]
你好，DNS域名解析服务已于 `3.0.32-rc` 版本提供，查看 [变更日志](https://github.com/huaweicloud/huaweicloud-sdk-python-v3/blob/master/CHANGELOG_CN.md#3032-rc-2021-01-30) 。如果您在使用中遇到问题，可以继续提交 Issue ，多谢。
