### ISSUE TITLE
ListCustomerselfResourceRecordsRequest is missing  `bill_date_<begin|end>` 

### ISSUE THREAD

**Issue by namoshizun** [huaweicloud/huaweicloud-sdk-python-v3#8]
Hi,

The `huaweicloudsdkbss` module seems to be a bit outdated.. While tuning the [billing API through portal](https://apiexplorer.developer.huaweicloud.com/apiexplorer/sdk?product=BSS&api=ListCustomerselfResourceRecords), the web page shows the API accepts "bill_date_begin" and "bill_date_begin" parameters, and the Python code example does the same thing, e.g.,:

```
        request = ListCustomerselfResourceRecordsRequest()
        request.cycle = "2021-01"
        request.region = "cn-south-1"
        request.offset = 0
        request.limit = 20
        request.enterprise_project_id = "0"
        request.include_zero_record = False
        request.bill_date_begin = "2021-01-18"
        request.bill_date_end = "2021-01-18"
```

However, the `huaweicloudsdkbss.v2.model.list_customerself_resource_records_request.ListCustomerselfResourceRecordsRequest` class (impressively long name by the way) doesn't have any definition for "bill_date_<begin|end>", nor the param was effective even if it is set...

**Comment by y30007935** [comment]
This is a new feature.Please try upgrade the SDK to the latest version for verification.

**Comment by y30007935** [comment]
> Hi,
> 
> The `huaweicloudsdkbss` module seems to be a bit outdated.. While tuning the [billing API through portal](https://apiexplorer.developer.huaweicloud.com/apiexplorer/sdk?product=BSS&api=ListCustomerselfResourceRecords), the web page shows the API accepts "bill_date_begin" and "bill_date_begin" parameters, and the Python code example does the same thing, e.g.,:
> 
> ```
>         request = ListCustomerselfResourceRecordsRequest()
>         request.cycle = "2021-01"
>         request.region = "cn-south-1"
>         request.offset = 0
>         request.limit = 20
>         request.enterprise_project_id = "0"
>         request.include_zero_record = False
>         request.bill_date_begin = "2021-01-18"
>         request.bill_date_end = "2021-01-18"
> ```
> 
> However, the `huaweicloudsdkbss.v2.model.list_customerself_resource_records_request.ListCustomerselfResourceRecordsRequest` class (impressively long name by the way) doesn't have any definition for "bill_date_<begin|end>", nor the param was effective even if it is set...

This is a new feature.Please try upgrade the SDK to the latest version for verification.

**Comment by namoshizun** [comment]
@y30007935 

I've upgraded to the following versions:
```
huaweicloudsdkbss              3.0.30rc0        
   
huaweicloudsdkcore             3.0.30rc0 
```
But the outcome is somehow getting worse. The API service seems to reject the "bill_date_end" parameter now and I received `400 Client Error: Bad Request for url`. I also tried it on the HWC API Explorer which also starts to throwing 400 error once I specified the "bill_date_end" param. I guess it is the remote API service not working properly now.

**Comment by yang7935** [comment]
> @y30007935
> 
> I've upgraded to the following versions:
> 
> ```
> huaweicloudsdkbss              3.0.30rc0        
>    
> huaweicloudsdkcore             3.0.30rc0 
> ```
> 
> But the outcome is somehow getting worse. The API service seems to reject the "bill_date_end" parameter now and I received `400 Client Error: Bad Request for url`. I also tried it on the HWC API Explorer which also starts to throwing 400 error once I specified the "bill_date_end" param. I guess it is the remote API service not working properly now.

Please check your request. The cycle field is mandatory. The values of bill_date_begin and bill_date_end must be in the same month as the cycle. For example:
![image](https://user-images.githubusercontent.com/77655835/105145972-5fe4e800-5b3a-11eb-9c72-5207b42ce5a8.png)

**Comment by yang7935** [comment]
@namoshizun 

Please check your request. The "cycle" parameter is mandatory. The values of "bill_date_begin" and "bill_date_end" must be in the same month as the "cycle". For example:
cycle=2021-01&bill_date_begin=2021-01-20&bill_date_end=2021-01-20

If the problem persists, Please contact the customer service at the official website.

**Comment by namoshizun** [comment]
> @namoshizun
> 
> Please check your request. The "cycle" parameter is mandatory. The values of "bill_date_begin" and "bill_date_end" must be in the same month as the "cycle". For example:
> cycle=2021-01&bill_date_begin=2021-01-20&bill_date_end=2021-01-20
> 
> If the problem persists, Please contact the customer service at the official website.


All good now~ that 400 issue might be due to some temporary upstream issue around that day.
Thanks.
