### ISSUE TITLE
README文档错误

### ISSUE THREAD

**Issue by ravizhan** [huaweicloud/huaweicloud-sdk-python-v3#9]
**README_CN.md**的`201`行和**README.md**的`203`行中的`print(respones)`有误，应改为`print(response)`

**Comment by Huaweicloud-SDK** [comment]
你好，感谢您的建议，我们在 `3.0.34-rc` 版本中对 **README.md** 和 **README_CN.md** 进行了调整，上述问题已经修改，如果对新的 README 格式和内容有疑问，请随时提交Issue，我们会尽快处理，多谢^^。
